### PR TITLE
Test verify, merge and release jobs

### PR DESCRIPTION
**Pull request by fdegir**

### CODE REVIEW

**Review by nordixinfra — COMMENTED** [review]
**EST Post Merge Verification**
- Build Status: **SUCCESS**
- Build URL: [est-nsm-meridio-experimental-merge-master](https://jenkins.nordix.org/job/est-nsm-meridio-experimental-merge-master/6/)

**Review by nordixinfra — COMMENTED** [review]
**Nordix Post Merge Verification**
- Build Status: **SUCCESS**
- Build URL: [nordix-nsm-meridio-experimental-merge-master](https://jenkins.nordix.org/job/nordix-nsm-meridio-experimental-merge-master/20/)

**Review by nordixinfra — COMMENTED** [review]
**EST Release**
- Build Status: **SUCCESS**
- Build URL: [est-nsm-meridio-experimental-release-master](https://jenkins.nordix.org/job/est-nsm-meridio-experimental-release-master/3/)

**Review by nordixinfra — COMMENTED** [review]
**EST Post Merge Verification**
- Build Status: **SUCCESS**
- Build URL: [est-nsm-meridio-experimental-merge-master](https://jenkins.nordix.org/job/est-nsm-meridio-experimental-merge-master/7/)

**Review by nordixinfra — COMMENTED** [review]
**EST Release**
- Build Status: **SUCCESS**
- Build URL: [est-nsm-meridio-experimental-release-master](https://jenkins.nordix.org/job/est-nsm-meridio-experimental-release-master/4/)

**Review by nordixinfra — COMMENTED** [review]
**Nordix Post Merge Verification**
- Build Status: **SUCCESS**
- Build URL: [nordix-nsm-meridio-experimental-merge-master](https://jenkins.nordix.org/job/nordix-nsm-meridio-experimental-merge-master/21/)

**Review by nordixinfra — COMMENTED** [review]
**Nordix Post Merge Verification**
- Build Status: **SUCCESS**
- Build URL: [nordix-nsm-meridio-experimental-merge-master](https://jenkins.nordix.org/job/nordix-nsm-meridio-experimental-merge-master/22/)

**Review by nordixinfra — COMMENTED** [review]
**EST Release**
- Build Status: **SUCCESS**
- Build URL: [est-nsm-meridio-experimental-release-master](https://jenkins.nordix.org/job/est-nsm-meridio-experimental-release-master/5/)

**Review by nordixinfra — COMMENTED** [review]
**EST Post Merge Verification**
- Build Status: **SUCCESS**
- Build URL: [est-nsm-meridio-experimental-merge-master](https://jenkins.nordix.org/job/est-nsm-meridio-experimental-merge-master/8/)

**Comment by fdegir** [comment]
/release my-tag

dummy comment

**Review by nordixinfra — COMMENTED** [review]
**EST Release**
- Build Status: **SUCCESS**
- Build URL: [est-nsm-meridio-experimental-release-master](https://jenkins.nordix.org/job/est-nsm-meridio-experimental-release-master/6/)

**Review by nordixinfra — COMMENTED** [review]
**Nordix Post Merge Verification**
- Build Status: **SUCCESS**
- Build URL: [nordix-nsm-meridio-experimental-merge-master](https://jenkins.nordix.org/job/nordix-nsm-meridio-experimental-merge-master/23/)

**Review by nordixinfra — COMMENTED** [review]
**EST Post Merge Verification**
- Build Status: **SUCCESS**
- Build URL: [est-nsm-meridio-experimental-merge-master](https://jenkins.nordix.org/job/est-nsm-meridio-experimental-merge-master/9/)

**Pull request merged**
