### PR TITLE
Test verify, merge and release jobs

### PR DESCRIPTION
**Pull request by fdegir**

### CODE REVIEW

**Review by nordixinfra — COMMENTED** [review]
**EST Post Merge Verification**
- Build Status: **SUCCESS**
- Build URL: [est-nsm-meridio-experimental-merge-master](https://jenkins.nordix.org/job/est-nsm-meridio-experimental-merge-master/10/)

**Review by nordixinfra — COMMENTED** [review]
**Nordix Post Merge Verification**
- Build Status: **SUCCESS**
- Build URL: [nordix-nsm-meridio-experimental-merge-master](https://jenkins.nordix.org/job/nordix-nsm-meridio-experimental-merge-master/24/)

**Comment by fdegir** [comment]
/release my-tag1

dummy comment

**Review by nordixinfra — COMMENTED** [review]
**EST Release**
- Build Status: **SUCCESS**
- Build URL: [est-nsm-meridio-experimental-release-master](https://jenkins.nordix.org/job/est-nsm-meridio-experimental-release-master/7/)

**Review by nordixinfra — COMMENTED** [review]
**EST Post Merge Verification**
- Build Status: **SUCCESS**
- Build URL: [est-nsm-meridio-experimental-merge-master](https://jenkins.nordix.org/job/est-nsm-meridio-experimental-merge-master/11/)

**Review by nordixinfra — COMMENTED** [review]
**EST Release**
- Build Status: **SUCCESS**
- Build URL: [est-nsm-meridio-experimental-release-master](https://jenkins.nordix.org/job/est-nsm-meridio-experimental-release-master/8/)

**Review by nordixinfra — COMMENTED** [review]
**Nordix Post Merge Verification**
- Build Status: **SUCCESS**
- Build URL: [nordix-nsm-meridio-experimental-merge-master](https://jenkins.nordix.org/job/nordix-nsm-meridio-experimental-merge-master/25/)

**Pull request merged**
