### PR TITLE
Test verify, merge and release jobs

### PR DESCRIPTION
**Pull request by fdegir**

### CODE REVIEW

**Review by nordixinfra — COMMENTED** [review]
**EST Post Merge Verification**
- Build Status: **SUCCESS**
- Build URL: [est-nsm-meridio-experimental-merge-master](https://jenkins.nordix.org/job/est-nsm-meridio-experimental-merge-master/31/)

**Review by nordixinfra — COMMENTED** [review]
**Nordix Post Merge Verification**
- Build Status: **SUCCESS**
- Build URL: [nordix-nsm-meridio-experimental-merge-master](https://jenkins.nordix.org/job/nordix-nsm-meridio-experimental-merge-master/45/)

**Comment by fdegir** [comment]
^/release my-tag6

**Comment by fdegir** [comment]
abdbc

/release 1.2.4

**Comment by fdegir** [comment]
askldjaskljd


  /release 1.2.5

**Comment by fdegir** [comment]
/remerge

test1

**Pull request merged**
