### PR TITLE
Nordix verify test22

### PR DESCRIPTION
**Pull request by fdegir**

### CODE REVIEW

**Comment by fdegir** [comment]
dummy comment

/release 1.0.10

dummy comment

**Comment by fdegir** [comment]
/release 1.0.11

dummy comment

**Review by nordixinfra — COMMENTED** [review]
**EST Release**
- Release tag: **RELEASE_TAG**
- Build Status: **SUCCESS**
- Build URL: [est-nsm-meridio-experimental-release-master-webhook](https://jenkins.nordix.org/job/est-nsm-meridio-experimental-release-master-webhook/77/)

**Review by nordixinfra — COMMENTED** [review]
**Release is OK!**
- Release tag: **1.0.19**
- Build Status: **SUCCESS**
- Build URL: [est-nsm-meridio-experimental-release-master-webhook](https://jenkins.nordix.org/job/est-nsm-meridio-experimental-release-master-webhook/78/)

**Pull request merged**
